### ISSUE TITLE
Lilly pilly trees quickly degrade after appearing

### ISSUE THREAD

**Issue by Wuzzy2** [vlapsley/outback#2]
Quickly after a lilly pilly tree appeared, the leaves and berries far away from the stem quickly degrade (leaf decay)
I think this should not be the case, the leaves and berries which spawn should usually be “safe” from leaf decay.

Maybe you just need to increase the leaf decay range (value of `leafdecay` group) for this tree.

**Comment by vlapsley** [comment]
leafdecay = 5 for all tree leaf nodes. The trees in the Australia mod are much larger than default Minetest Game trees.
