### ISSUE TITLE
Make stone pebbles more useful

### ISSUE THREAD

**Issue by Wuzzy2** [vlapsley/outback#5]
Suggestion:

- Make (red) stone pebbles diggable by hand
- Make pickaxe dig time for pebbles much shorter
- Add craft:  9 (red) stone pebbles give 1 (red) cobblestone.
- Add stone pebbles to other biomes in the world

This will give the player an interesting new way to craft tools, different from the odd “tree punching”. :D

What do you think about this?

**Comment by vlapsley** [comment]
Commit https://github.com/vlapsley/outback/commit/4bb1cb5f75f6bd6f64a5dec0d2286f3f5843b014 introduces small rocks, replacing the pebble.

Modified code from duane-r [valleys_c](https://github.com/duane-r/valleys_c/blob/master/deco_rocks.lua)
I like the look of the little cubes vs. the pebbles sphere. Fits with the game better, IMO.

3 types: red stone, sandstone and default stone. 4 small rocks is craftable into cobble.

I've made a sandstone cobble node. I'm not sure about the texture though.

I'll nerf tree-punching in a future commit.
